### ISSUE TITLE
[BUG] 开机时日志报错

### ISSUE THREAD

**Issue by LoveCatc** [Simplicity-Team/SimplicityTools#106]
**描述一下BUG情况**
在LSPosed日志中可以见到不明报错；在更换某些第三方主题时有几率无法开机（卡重启）如主题商店的【蜂巢】。
**如何复现**
复现的步骤：
在SimplicityTools的主题更改中隐藏蓝牙、HD图标、勿扰图标，打开时钟显秒的情况下，每次重启即可在LSPosed日志中看到相应报错。

**截图**
![image](https://user-images.githubusercontent.com/48412571/159854122-7c250ae9-6534-4abf-b96a-84624c4651dd.png)

**手机信息：**
 - 设备型号：MIX4 (odin)
 - MIUI版本：13.0.4稳定版
 - Android版本：android12

**附加信息**
LSPosed信息：
API 版本
93

注入接口
Zygisk

框架版本
1.7.2 (6379)

管理器版本
1.7.2 (6379)

系统版本
12 (API 31)

设备
Xiaomi 2106118C 

系统架构
arm64-v8a

完整日志：

```
----part 1 start----
[ 2022-03-24T14:08:54.393     1000:  1597:  1597 I/LSPosed-Bridge  ] Loading module com.github.tianma8023.xposed.smscode from /data/app/~~0F9DiCSghl84H6sgVhkFzA==/com.github.tianma8023.xposed.smscode-9jzhN6KjiK5TBy0WmnpeFg==/base.apk
[ 2022-03-24T14:08:54.405     1000:  1597:  1597 I/LSPosed-Bridge  ]   Loading class com.tianma.xsmscode.xp.HookEntry
[ 2022-03-24T14:08:54.418     1000:  1597:  1597 I/LSPosed-Bridge  ] Loading module com.yuk.fuckMiuiThemeManager from /data/app/~~0HoiiUrbzLCamPmjiOr3jw==/com.yuk.fuckMiuiThemeManager-VrREeGqm2Un-nWfBZ-18Pw==/base.apk
[ 2022-03-24T14:08:54.418     1000:  1597:  1597 I/LSPosed-Bridge  ]   Loading class com.yuk.fuckMiuiThemeManager.XposedInit
[ 2022-03-24T14:08:54.420     1000:  1597:  1597 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:08:54.421     1000:  1597:  1597 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:08:55.346     1000:  1597:  1597 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook Android
[ 2022-03-24T14:08:55.469     1000:  1597:  1597 I/LSPosed-Bridge  ] SimplicityTools: java.lang.NoSuchMethodError: com.android.server.wm.WallpaperController#WallpaperController(android.app.Service,android.icu.text.DisplayContext)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at t0.e.o(Unknown Source:5)
	at com.lt2333.simplicitytools.hook.app.android.MaxWallpaperScale.handleLoadPackage(:6)
	at com.lt2333.simplicitytools.hook.app.Android.handleLoadPackage(Unknown Source:44)
	at com.lt2333.simplicitytools.hook.MainHook.handleLoadPackage(:4)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at p.beforeHookedMethod(Unknown Source:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:893)
	at com.android.server.SystemServer.main(SystemServer.java:621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1023)
[ 2022-03-24T14:09:16.584     1001:  4058:  4058 I/LSPosed-Bridge  ] Loading module com.github.tianma8023.xposed.smscode from /data/app/~~0F9DiCSghl84H6sgVhkFzA==/com.github.tianma8023.xposed.smscode-9jzhN6KjiK5TBy0WmnpeFg==/base.apk
[ 2022-03-24T14:09:16.593     1001:  4058:  4058 I/LSPosed-Bridge  ]   Loading class com.tianma.xsmscode.xp.HookEntry
[ 2022-03-24T14:09:16.614     1000:  4061:  4061 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:16.618     1000:  4061:  4061 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:16.650    10082:  4111:  4111 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:16.655    10082:  4111:  4111 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:16.753     1000:  4061:  4061 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook SystemUI
[ 2022-03-24T14:09:16.822    10082:  4111:  4111 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook MiuiHome
[ 2022-03-24T14:09:18.830     1000:  4622:  4622 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:18.833     1000:  4622:  4622 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:18.956     1000:  4622:  4622 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook Settings
[ 2022-03-24T14:09:27.225     1000:  6091:  6091 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:27.229     1000:  6091:  6091 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:27.697     1000:  6091:  6091 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook SecurityCenter
[ 2022-03-24T14:09:27.824     6102:  6404:  6404 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:27.829     6102:  6404:  6404 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:29.958     1000:  7357:  7357 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:29.965     1000:  7357:  7357 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:30.362     1000:  7357:  7357 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook SecurityCenter
[ 2022-03-24T14:09:31.239     1000:  8034:  8034 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:31.303     1000:  8034:  8034 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:31.655     1000:  8034:  8034 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook PowerKeeper
[ 2022-03-24T14:09:33.517     1000:  8944:  8944 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~XAEfHyuRQJfmvg-a0kmB9Q==/com.lt2333.simplicitytools-3J-ATWgHsxw4mx8dBl-kDQ==/base.apk
[ 2022-03-24T14:09:33.521     1000:  8944:  8944 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.MainHook
[ 2022-03-24T14:09:33.677     1000:  8944:  8944 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook Settings
[ 2022-03-24T14:09:38.426    10277:  9574:  9574 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~qhwfjHNZVoJTxyPEZBzexw==/nil.nadph.qnotified-iLImRogWsIuxrqt8njXVLw==/base.apk
[ 2022-03-24T14:09:38.460    10277:  9574:  9574 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2022-03-24T14:09:39.177    10277:  9659:  9659 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~qhwfjHNZVoJTxyPEZBzexw==/nil.nadph.qnotified-iLImRogWsIuxrqt8njXVLw==/base.apk
[ 2022-03-24T14:09:39.209    10277:  9659:  9659 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2022-03-24T14:09:58.900    10330: 11861: 11861 I/LSPosed-Bridge  ] Loading module org.hello.coolapk from /data/user/0/com.coolapk.market/cache/lspatch/org.hello.coolapk/2936222053
[ 2022-03-24T14:09:58.910    10330: 11861: 11861 I/LSPosed-Bridge  ]   Loading class org.fuck.coolapk.XposedEntry
[ 2022-03-24T14:09:59.353    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: {removeFeedAdsEnhance=false, bannerPic=https://cdn.jsdelivr.net/gh/ejiaogl/FuckCoolapk@master/art/316/316-2.png, removeBannerAds=true, bannerUrl=https://316.coolapk1s.com, removeFeedAds=true, removeFeedGoods=true, removeUpdateDialog=true, redirectLink=www.coolapk1s.com}
[ 2022-03-24T14:09:59.747    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: private void com.coolapk.market.CoolMarketApplication.ؠ()
[ 2022-03-24T14:09:59.933    10330: 12209: 12209 I/LSPosed-Bridge  ] Loading module org.hello.coolapk from /data/user/0/com.coolapk.market/cache/lspatch/org.hello.coolapk/2936222053
[ 2022-03-24T14:09:59.944    10330: 12209: 12209 I/LSPosed-Bridge  ]   Loading class org.fuck.coolapk.XposedEntry
[ 2022-03-24T14:09:59.965    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.main.MainActivity
[ 2022-03-24T14:10:00.545    10330: 12209: 12209 I/LSPosed-Bridge  ] FuckCoolApk: {removeFeedAdsEnhance=false, bannerPic=https://cdn.jsdelivr.net/gh/ejiaogl/FuckCoolapk@master/art/316/316-2.png, removeBannerAds=true, bannerUrl=https://316.coolapk1s.com, removeFeedAds=true, removeFeedGoods=true, removeUpdateDialog=true, redirectLink=www.coolapk1s.com}
[ 2022-03-24T14:10:01.357    10330: 12209: 12209 I/LSPosed-Bridge  ] FuckCoolApk: private void com.coolapk.market.CoolMarketApplication.ؠ()
[ 2022-03-24T14:10:02.990    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.search.SuperSearchActivity
[ 2022-03-24T14:10:09.128    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.search.SuperSearchResultActivity
[ 2022-03-24T14:10:11.366    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.node.DynamicNodePageActivity
[ 2022-03-24T14:10:17.048    10277: 14871: 14871 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~qhwfjHNZVoJTxyPEZBzexw==/nil.nadph.qnotified-iLImRogWsIuxrqt8njXVLw==/base.apk
[ 2022-03-24T14:10:17.079    10277: 14871: 14871 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2022-03-24T14:10:19.871    10277: 15142: 15142 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~qhwfjHNZVoJTxyPEZBzexw==/nil.nadph.qnotified-iLImRogWsIuxrqt8njXVLw==/base.apk
[ 2022-03-24T14:10:19.905    10277: 15142: 15142 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2022-03-24T14:10:20.258    10277: 15211: 15211 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~qhwfjHNZVoJTxyPEZBzexw==/nil.nadph.qnotified-iLImRogWsIuxrqt8njXVLw==/base.apk
[ 2022-03-24T14:10:20.292    10277: 15211: 15211 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2022-03-24T14:10:23.082    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.photo.PhotoViewActivity
[ 2022-03-24T14:10:40.839    10330: 11861: 11861 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.photo.PhotoViewActivity

```

**Comment by LittleTurtle2333** [comment]
已修复

**Comment by LoveCatc** [comment]
[自动回复]您好，我已收到您的邮件。感谢您的来信。
