### ISSUE TITLE
[BUG]MIUI 13.0.3 Mi 10S系统界面崩溃

### ISSUE THREAD

**Issue by Steven-nagisa-Y** [Simplicity-Team/SimplicityTools#131]
**描述一下BUG情况**
使用过程中界面突然黑屏，几秒钟后显示锁屏页面。
应该是系统界面崩溃重启了。

**如何复现**
无法手动复现。
偶然出现，频率大约两三天一次。

**截图**
没有截图，有log

**手机信息：**
 - 设备型号：小米 10S
 - MIUI版本：MIUI 13.0.3 稳定版
 - Android版本：12

**附加信息**
log:
```log
[ 2022-04-04T09:12:00.921     1000:  3132:  3132 I/LSPosed-Bridge  ] SimplicityTools: Error occurred calling hooker on private final void com.android.systemui.statusbar.views.MiuiClock.updateTime()
[ 2022-04-04T09:12:00.923     1000:  3132:  3132 I/LSPosed-Bridge  ] SimplicityTools: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1282536 free bytes and 1252KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at libcore.util.ZoneInfo.clone(ZoneInfo.java:303)
	at java.util.TimeZone.getDefault(TimeZone.java:702)
	at java.util.Calendar.getInstance(Calendar.java:1625)
	at N.f.afterHookedMethod(:1)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.updateTime(Unknown Source:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at h.h.run(:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
[ 2022-04-04T09:12:01.652     1000:  3132:  3816 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 40704 free bytes and 39KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at V.M.run(Unknown Source:0)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
[ 2022-04-04T09:12:01.654     1000:  3132:  3816 E/AndroidRuntime  ] FATAL EXCEPTION: Timer-0
Process: com.android.systemui, PID: 3132
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 40704 free bytes and 39KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at V.M.run(Unknown Source:0)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
[ 2022-04-04T09:12:02.370     1000:  3132:  3213 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.OutOfMemoryError: Failed to allocate a 88 byte allocation with 1272728 free bytes and 1242KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.app.NotificationChannel$1.createFromParcel(NotificationChannel.java:1235)
	at android.app.NotificationChannel$1.createFromParcel(NotificationChannel.java:1232)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.service.notification.NotificationListenerService$Ranking.<init>(NotificationListenerService.java:1765)
	at android.service.notification.NotificationListenerService$RankingMap.<init>(NotificationListenerService.java:2197)
	at android.service.notification.NotificationListenerService$RankingMap.<init>(NotificationListenerService.java:2173)
	at android.service.notification.NotificationListenerService$RankingMap$1.createFromParcel(NotificationListenerService.java:2233)
	at android.service.notification.NotificationListenerService$RankingMap$1.createFromParcel(NotificationListenerService.java:2230)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.service.notification.NotificationRankingUpdate.<init>(NotificationRankingUpdate.java:33)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:62)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:60)
	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:250)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)
[ 2022-04-04T09:12:02.370     1000:  3132:  3213 E/AndroidRuntime  ] FATAL EXCEPTION: Binder:3132_2
Process: com.android.systemui, PID: 3132
java.lang.OutOfMemoryError: Failed to allocate a 88 byte allocation with 1272728 free bytes and 1242KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.app.NotificationChannel$1.createFromParcel(NotificationChannel.java:1235)
	at android.app.NotificationChannel$1.createFromParcel(NotificationChannel.java:1232)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.service.notification.NotificationListenerService$Ranking.<init>(NotificationListenerService.java:1765)
	at android.service.notification.NotificationListenerService$RankingMap.<init>(NotificationListenerService.java:2197)
	at android.service.notification.NotificationListenerService$RankingMap.<init>(NotificationListenerService.java:2173)
	at android.service.notification.NotificationListenerService$RankingMap$1.createFromParcel(NotificationListenerService.java:2233)
	at android.service.notification.NotificationListenerService$RankingMap$1.createFromParcel(NotificationListenerService.java:2230)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.service.notification.NotificationRankingUpdate.<init>(NotificationRankingUpdate.java:33)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:62)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:60)
	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:250)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)
[ 2022-04-04T09:12:05.120     1000: 30232: 30232 I/LSPosed         ] Loading xposed for com.android.systemui/1000
......
[ 2022-04-04T09:14:06.307     1000:  2458:  2458 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hook.XposedEntry
[ 2022-04-04T09:14:06.360     1000:  2458:  2458 I/LSPosed-Bridge  ] Simplicitytools: 成功 Hook ScreenShot
[ 2022-04-04T09:14:06.369     1000:  2458:  2458 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:19)
	at S.a.b(Unknown Source:24)
	at com.lt2333.simplicitytools.util.xposed.base.AppRegister.a(:3)
	at com.lt2333.simplicitytools.hook.app.ScreenShot.handleLoadPackage(Unknown Source:15)
	at com.lt2333.simplicitytools.util.xposed.EasyXposedInit.handleLoadPackage(:5)
	at com.lt2333.simplicitytools.hook.XposedEntry.handleLoadPackage(Unknown Source:11)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at H.afterHookedMethod(Unknown Source:104)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1320)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3024)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3016)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
	at LSPHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1600(ActivityThread.java:264)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by LittleTurtle2333** [comment]
在LSPosed右上角导出完整log包给我看看

**Comment by Steven-nagisa-Y** [comment]
大约在2022-04-08 19:00 系统界面突然卡顿然后黑屏，接着显示锁屏界面。
当然是根据我这边主观判断是由本模块构成，因为之前在用MIUI 12.5，没有安装过本模块，就没有出现这个问题。升级MIUI 13/Android 12之后并使用了本模块之后出现了这种间歇性黑屏的问题。如果不是本模块的bug，还望大佬看看是不是其他模块冲突了，要怎么解决？
LSPosed压缩包在[QQ邮箱中转站](https://wx.mail.qq.com/ftn/download?func=3&key=cccb156500cd5a01feb84f656134316189e10a6563343161161b02075055090502054c5d0650014c070204014e0d5300051959540650095955515700510c12617f67310a1051553e010453574e04054c030c35545b6b04586c01594b5205064f495d1171447cc14d672e3579fe3fd047e9c3e06966f5b102&code=34aec41a&k=cccb156500cd5a01feb84f656134316189e10a6563343161161b02075055090502054c5d0650014c070204014e0d5300051959540650095955515700510c12617f67310a1051553e010453574e04054c030c35545b6b04586c01594b5205064f495d1171447cc14d672e3579fe3fd047e9c3e06966f5b102&fweb=1&cl=1)

**Comment by LittleTurtle2333** [comment]
你这应该是系统层面的问题了，我看其他模块也有这个异常

**Comment by Steven-nagisa-Y** [comment]
那只有等待下一次系统更新看能不能好些

**Comment by Steven-nagisa-Y** [comment]
问题大概是解决了，LSPosed更新了1.8.1版本之后，再没出现过系统界面崩溃的问题
